# git aliases
alias d="git diff"
alias ga="git add ."
alias gb="git branch"
alias cm="git commit -m"
alias co="git checkout"
alias gp="git push"
alias gpl="git pull"
alias gl="git log"
alias gm="git merge"
alias grb="git rebase"
alias gsh="git stash"
alias gsp="git stash pop"
alias gs="git status"
alias db="git branch -D"
